[package]
name = "libtashkeel"
version = "0.1.0"
edition = "2021"


[lib]
name = "libtashkeel"
crate-type = ["cdylib"]

[dependencies]
libtashkeel_base = { path = "../libtashkeel_base" }
ffi-support = "0.4.4"
libc = "0.2.140"
